### ISSUE TITLE
Off-By-One Bug

### ISSUE THREAD

**Issue by dk2git** [adobe-fonts/adobe-variable-font-prototype#3]
This font (AdobeVFPrototype.oft version 1.001 released on Nov 13, 2016) has a bug in one of the Font DICTs. According to the header, the length of the problematic dictionary is 8 bytes, which means the dictionary's valid byte range is [0..7]. However, the last operand in the dictionary begins at offset 5 from the start of the dictionary and its length is 4 bytes (meaning the operand occupies byte locations 5, 6, 7 and 8). Obviously, this 4th byte is outside the dictionary's valid range [0..7], which makes the last operand invalid. To fix this off-by-one bug, the length of the dictionary should be set to 9 bytes.

**Comment by readroberts** [comment]
Noted. Good catch! Will fix this soon.

**Comment by readroberts** [comment]
I can't see this problem. I downloaded the font file 'AdobeVFPrototype.otf' from the "latest release page" from this project. I see, using 'spot -t name=3 'AdobeVFPrototype.otf', that the version is the same as what you looked at, 1.001, and creation date Sun Nov 13 17:55:52 2016. However, the Top DICT I see is correct. I dumped the CFF2 table with 'tx -dcf -5 <font file", and see that the TopDICT spans byte offsets x00001f65-0x00001f70 inclusive, or 12 bytes. The contents are:
  146396 FDArray # 2 bytes for the operator, 5 bytes for the value.
  115 CharStrings # one byte for the operator, two bytes for the value
  21 VarStore # one byte for the operator, one for the value
This totals to 12 bytes, which matches. If I extract the CFF2 table to a file with 'sfntedit -x CFF2 <font-file>, and then look at a hex dump of the file, I see that the  the header is "02 00 05 00 0C", of which the last two bytes are the Top Dict length, which is 12. When I rebuild the font from sources, I get  slightly different data, using the latest FDK. The header is then "02 00 05 00 0B", for a top Dict length of 11 (0x000B), which matches the length of the Top DICT data for this version font. How did you inspect the font data, and was it the OTF in the release page, or one that you build from the source data?

**Comment by dk2git** [comment]
And why are you debugging the Top DICT?? I reported a bug in the Font DICT. This dict starts at byte offset x00025b41 and has a declared length of 8 bytes (which should be 9).

**Comment by readroberts** [comment]
Hello dk2git;
I was confused by because you said "one of the Font DICTs",  and there is only one Font DICT in the FDArray.  Historically, the Top DICT is also often referred to as a FontDICT. This is a bit of reach, but then you  also said that the length of the DICT is given by a header, and the only header which describes a  DICT length is the CFF2 header, which gives the length of the Top DICT. The length of a Font DICT in the FDArray is implied by the difference between two successive offsets.

The font data does  looks correct to me. I parse this as follows

The dump from tx-dcf -1 <font-file> is

### FDArray INDEX (00025b3c-00025b4a)
count  =1
offSize=1
--- offset[index]=value
[0]=1
[1]=9
--- object[index]={value}
[0]={
  193 146411 Private
}

This is also what in see in hex dump of the file. The hex string is in :
00025B30: 05 8B FB 15 8D 9D 95 85 81 8C 10 05 00 00 00 01 	.ã˚.çùïÖÅå......
00025B40: 01 01 09 F7 55 1D 00 02 3B EB 12 77 9F F8 7B 9B 	...˜U...;Î.wü¯{õ

The FDArray data is in the range 00025b3c-00025b4a inclusive, for a total of 15 bytes.

The FDArray count is the 4 bytes from 00025b3c to 00025b3f, inclusive
00 00 00 01 -> FDArray.count =1

The offset size is 1 byte at 00025B40:
01 => FDArray.offSize =1

The first offset is at 00025B41:
01 => FDArray. offset 0  =1

The second offset is at 00025B42:
01 => FDArray. offset 1  =9

The Font Dict covers the 8 bytes 00025B43 to 00025b4a: 
F7 55 1D 00 02 3B EB 12

The first two bytes are the Private DICT size
The next 5 bytes are the Private DICT offset
The last byte is the Private dict operator, 0x12.

You will notice that the Font DICT size is given by the difference between the offset values, divided by the offset size. This is 8 bytes.

How do you parse this hex string?

**Comment by dk2git** [comment]
I used my own code (which is a modified version of the code originally used to parse the CFF format) to parse the Dict. After just reviewing the CFF2 specification once again (and specifically Appendix D Changes From CFF 1.0), I see that in CFF2 the count field of an INDEX is uint32 instead of uint16. The new CFF2 specification that was posted on January 6, 2017 is a lot more clear in this regard. Even before the new specs, I think this was mentioned but it did not caught my attention. This is probably one of those changes that need to be really prominently stated.

Anyway, due to that difference in the data type, my code was incorrectly calculating the offset of the Font DICT, so it started parsing earlier than it should (by 2 bytes). This then resulted in wrong data to read and the size mismatch at the end of the dict. After updating my code to use uint32 for the count filed, my results are the same as yours.

So this was a false alarm and the issue can be closed. Thanks for your analysis and sorry for any trouble/confusion caused.

**Comment by readroberts** [comment]
I'm glad that it data is correct. I don't mind the time to check - in general, it is of great value to have  independent code bases like yours, as these help catch errors and point out confusing errors in the specifications.
